# Simple Arithmetic

In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4,5,6])

newarr=np.add(arr1,arr2)
print(newarr)

[ 2  4  6  8 10 12]


In [6]:
arr1=np.array([10,2,56,29,10,3])
arr2=np.array([3,5,2,6,7,3])

newarr=np.subtract(arr1,arr2)
print(newarr)

[ 7 -3 54 23  3  0]


In [7]:
arr1=np.array([10,2,56,29,10,3])
arr2=np.array([3,5,2,6,7,3])

newarr=np.multiply(arr1,arr2)
print(newarr)

[ 30  10 112 174  70   9]


In [9]:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  716276736 -520093696       2500          0]


In [12]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  0  0  0  0 27]


 You get the same result when using the remainder() function:

In [13]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [14]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]
