In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)      

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)                                

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((5,5),dtype='i')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [13]:
np.ones((5,5),dtype='i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [18]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [24]:
np.eye(5,dtype='i')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [33]:
np.random.rand(5)

array([0.02443758, 0.74879067, 0.40505905, 0.84444045, 0.63191914])

In [31]:
np.random.randint(1,100)

11

In [35]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr=np.random.randint(1,100,10)
ranarr

array([13,  1, 80, 73,  7, 96, 64, 65, 78, 94])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr.min()

1

In [47]:
ranarr.max()

96

In [49]:
ranarr

array([13,  1, 80, 73,  7, 96, 64, 65, 78, 94])

In [52]:
ranarr.argmax()    # it will return the index of max value.
ranarr.argmin()    # it will return the index of min value.

1

In [56]:
arr.shape

(25,)

In [57]:
arr.dtype

dtype('int32')