# Arithmatic Operations on Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a+2

array([3, 4, 5, 6, 7])

In [4]:
a-2

array([-1,  0,  1,  2,  3])

In [5]:
a*2

array([ 2,  4,  6,  8, 10])

In [6]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
a**2

array([ 1,  4,  9, 16, 25])

In [8]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [9]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [12]:
# Trignomatric functions
np.sin(a)
np.cos(a[0])

0.5403023058681398

# Linear Algebra

In [21]:
a=np.array([[1,2],[3,4]])
print(a)

print()
b=np.array([[4,6],[8,3]])
print(b)

print()
c=np.multiply(a,b)
print(c)

[[1 2]
 [3 4]]

[[4 6]
 [8 3]]

[[ 4 12]
 [24 12]]


In [25]:
a=np.array([[1,2,3],[4,5,6],[7,5,9]])
np.linalg.det(a)

-17.999999999999996

In [26]:
# Eigen value of square matrix
np.linalg.eig(a)

(array([14.91913036, -1.05871923,  1.13958886]),
 array([[ 0.25051705,  0.80902861, -0.02715089],
        [ 0.57302626,  0.04615057, -0.83232617],
        [ 0.78030899, -0.58595463,  0.55362079]]))

In [27]:
# Scipy me mil jayenge yeh sab aur sab functions.......

# Statistics

In [34]:
a= np.array([[1,2,3],[0,4,6]])
a

array([[1, 2, 3],
       [0, 4, 6]])

In [36]:
# Row wise min
np.min(a,axis=1) 

array([1, 0])

In [35]:
# column wise min
np.min(a,axis=0) 

array([0, 2, 3])

In [37]:
# min element
np.min(a)

0

In [38]:
# Row wise max
np.max(a,axis=1) 

array([3, 6])

In [39]:
# column wise max
np.max(a,axis=0)

array([1, 4, 6])

In [40]:
# max element
np.max(a)

6

In [41]:
# sum of elements
np.sum(a)

16

In [42]:
# row wise sum
np.sum(a,axis=1)

array([ 6, 10])

In [43]:
# column wise sum
np.sum(a,axis=0)

array([1, 6, 9])

In [47]:
# mean , median
a=np.array([[1,2,3],[4,5,6]])
print(np.mean(a))
print(np.median(a))

3.5
3.5


In [48]:
# standard deviation
np.std(a)

1.707825127659933

In [49]:
# variation
np.var(a)

2.9166666666666665

# Linear Equations

     4x - 5y = 13
     5x - 3y = 7

In [52]:
coeff1=np.array([[1,-5],[5,-3]])
coeff2=np.array([13,7])

np.linalg.solve(coeff1,coeff2)

array([-0.18181818, -2.63636364])