In [1]:
print("Hello jupyter")

Hello jupyter


### Heading

In [2]:
import numpy as np

In [11]:
a=np.array([1,2,3,4,5])
print(a)
print(a[0])
print(a[-1])

[1 2 3 4 5]
1
5


In [15]:
# 2-D array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


In [20]:
# get shape
b.shape

(2, 4)

In [27]:
# reshape array
x=np.array([1,2,3,4,5,6,7,8])
print(x)

print()
y=x.reshape(2,4)
print(y)

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
# get type
a.dtype
b.dtype

dtype('int32')

In [30]:
# get size
a.itemsize

4

In [31]:
# get total size
a.nbytes

20

In [35]:
# get number of elements
print(a.size)
print(b.size)

5
8


# Accessing / Changing specific elements , rows , columns, etc..

In [37]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
# get a specific elements (r,c)
a[1,4]

10

In [43]:
# get a specific row
print(a[1,:])
print(a[0,:])

[ 6  7  8  9 10]
[1 2 3 4 5]


In [46]:
# get a specific column
print(a[:,3])

[4 9]


In [47]:
# [start:end:stepsize]
a[0,1:5:2]

array([2, 4])

In [51]:
# update an element
a[1,4]=25
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 25]]


In [55]:
# update elements
a[:,3]=5
print(a)

print()
a[1,:]=45
print(a)

print()
a[:,2]=[18,19]
print(a)

[[ 1  2 18  5  5]
 [45 45 19  5 45]]

[[ 1  2 18  5  5]
 [45 45 45 45 45]]

[[ 1  2 18  5  5]
 [45 45 19 45 45]]


# 3-D Array

In [62]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
c[1,:,:]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[5, 6],
       [7, 8]])

## Initializing Different Types of Arrays

In [67]:
# All 0's matrix
a=np.zeros((2,3),dtype='i')
print(a)

[[0 0 0]
 [0 0 0]]


In [69]:
# All 1's matrix
x= np.ones((4,2,3),dtype='i')
print(x)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [71]:
# Any other value

y=np.full((2,2,2),27)
y

array([[[27, 27],
        [27, 27]],

       [[27, 27],
        [27, 27]]])

In [72]:
# Any other number (full_like)
y=np.full_like(y,56)
print(y)

[[[56 56]
  [56 56]]

 [[56 56]
  [56 56]]]


In [78]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.09120881, 0.61756986],
       [0.41845498, 0.0355386 ],
       [0.54039137, 0.62574194],
       [0.49007549, 0.29125784]])

In [81]:
# Random integer number
np.random.rand(2,4)

array([[0.27051885, 0.65692183, 0.86758962, 0.80507788],
       [0.22602791, 0.73182954, 0.49941194, 0.52408957]])

In [84]:
# the identity matrix
np.identity(5,dtype='i')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

# Copy and Other operations

In [86]:
a=np.array([1,2,3,4])
b=a.copy()

b[0]=67
print(a)
print(b)

[1 2 3 4]
[67  2  3  4]
