In [1]:
import numpy as np


In [4]:
arr=np.array([1,3,7,2,0,6])
newarr=np.sort(arr)
print(newarr)

[0 1 2 3 6 7]


In [5]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [6]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [7]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
