In [2]:
import numpy as np

In [7]:
arr =np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.26.2


In [5]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]
