In [1]:
import numpy as np

In [3]:
#                         ****** Slicing arrays******

# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])


[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [7]:
# Negative Slicing
# Use the minus operator to refer to an index from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [10]:
# STEP
# Use the step value to determine the step of the slicing:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:7:2])

[2 4 6]


In [11]:
print(arr[::2])

[1 3 5 7]


In [12]:
# Slicing 2-D Arrays
# Example

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [28]:
print(arr[0:2, 4])


[ 5 10]


#### print(arr[0:2, 1:4])

In [29]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
