In [2]:
import numpy as np

In [ ]:
# What is a Random Number ?
#   Random means something that can not be predicted logically.

# Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

In [3]:
from numpy import random

In [6]:
# Generate a random integer from 0 to 100:

x=random.randint(100)
print(x)

11


In [9]:
# Generate Random Float
# The random module's rand() method returns a random float between 0 and 1.

x = random.rand()

print(x)

0.42126273794498037


In [10]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

x=random.randint(50,size=(5))
print(x)

[37 49 39  3 11]


In [12]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(50, size=(3, 5))

print(x)                                                                                                             

[[23 14  9  0  6]
 [22 48 33 18 47]
 [44 21  5 30 13]]


In [13]:
# Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)

[0.73977482 0.70396268 0.63506756 0.23587628 0.73291027]


In [20]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:

from numpy import random

x = random.rand(3, 5)

print(x)

[[0.04825503 0.79925891 0.2799176  0.09017123 0.67857135]
 [0.46794737 0.57353901 0.50427134 0.4244382  0.4556197 ]
 [0.01271374 0.34430649 0.43381011 0.52460032 0.71765066]]


In [ ]:
# Generate Random Number From Array
# The choice() method allows you to generate a random value based on an array of values.

# The choice() method takes an array as a parameter and randomly returns one of the values.



In [26]:
from numpy import random

x = random.choice([1,2,3,4,5,6])

print(x)

1


In [22]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 7 7 9 7]
 [7 3 3 7 7]
 [7 7 3 7 7]]
