In [1]:
import numpy as np

In [3]:
#  0-D Array

arr=np.array(42)
print(arr)

42


In [4]:
# 1-D Arrays

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
# 2-D Arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3-D arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
# Check Number of Dimensions?
# NumPy Arrays provides the  "ndim"  attribute that returns an integer that tells us how many dimensions the array have.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
# Higher Dimensional Arrays

arr = np.array([1, 2, 3, 4], ndmin=32)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
number of dimensions : 32
