In [7]:
import numpy as np

In [8]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [10]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
# get dimension
a.ndim

2

In [12]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [26]:
y= x.reshape(4,2)
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
x.dtype

dtype('int32')

In [18]:
x.shape

(8,)

In [27]:
x.itemsize

4

In [28]:
x.nbytes

32

In [29]:
x.size

8

## Accessing/changing specific elements,rows,column,etc..

In [31]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
a[1,5]

12

In [36]:
a[1,:]
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [37]:
a[:,2]

array([3, 9])

In [38]:
a[0,1:5:2]

array([2, 4])

In [40]:
a[1,5]=17
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 17]]


In [41]:
a[:,4]=8
print(a)

[[ 1  2  3  4  8  6]
 [ 7  8  9 10  8 17]]


In [42]:
a[1,:]=2
print(a)

[[1 2 3 4 8 6]
 [2 2 2 2 2 2]]


In [48]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [52]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c[0,1:,:])

[[3 4]]


In [45]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
np.zeros((5,5,5),int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [58]:
np.full((5,5),11)

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [65]:
import random
np.random.randint(1,6,size=(5,5))

array([[1, 4, 4, 1, 5],
       [2, 2, 3, 5, 4],
       [4, 1, 4, 1, 1],
       [1, 4, 2, 2, 5],
       [5, 3, 3, 4, 2]])

In [67]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


# Numpy Operations - 

In [69]:
a=np.array([1,2,3,4,5])
a+2

array([3, 4, 5, 6, 7])

In [70]:
a-2

array([-1,  0,  1,  2,  3])

In [71]:
a*2

array([ 2,  4,  6,  8, 10])

In [72]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [73]:
a**2

array([ 1,  4,  9, 16, 25])

In [74]:
a//2

array([0, 1, 1, 2, 2], dtype=int32)

In [83]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c= a+b
c

array([ 2,  4,  6,  8, 10])

In [84]:
np.sin(c[0])
np.cos(c[0])

-0.4161468365471424

In [86]:
# matrix multiplication -->
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [89]:
np.linalg.det(a)

-2.0000000000000004

In [90]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [93]:
np.min(a)

1

In [94]:
np.max(a)

4

In [96]:
np.min(a,axis=1)

array([1, 3])

In [100]:
np.sum(a,axis=0) #columnwise ke liye

array([3, 7])

In [101]:
np.sum(a,axis=1)

array([3, 7])

In [104]:
np.median(a)

2.5

In [ ]:
# variation=(std deviation)^2

# linear Algebra
solve this equations - 

 4x+6y=12

 2x+4y=24

In [106]:
coeff1=np.array([[4,6],[2,4]])
coeff2=np.array([12,24])
res = np.linalg.solve(coeff1,coeff2)
res

array([-24.,  18.])